name: Build and Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - run: |
        python -m pip install --upgrade pip
        pip install customtkinter requests PyGithub pyinstaller

    - name: Build
      working-directory: ./windows
      run: |
        python -m PyInstaller --noconsole --onefile --name "X-Fetch" --clean main.py
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          mv dist/X-Fetch dist/X-Fetch-Linux
        else
          mv dist/X-Fetch dist/X-Fetch-MacOS
        fi

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "v1.0.0"
        name: "Linux and MacOS Builds"
        files: windows/dist/X-Fetch-*
